### ISSUE TITLE
[Not An Issue] Just wanted to highlight a reshare

### ISSUE THREAD

**Issue by Dan-Q** [jps327/satc-polycule-app#1]
👋 I'm struggling to contact you (did you know the contact form at https://pablowritescode.com/contact/ is broken?). Just so it doesn't get lost, here's a message I was trying to send you. Feel free to delete this issue!

----

Loved your !!Con talk, which I saw on YouTube yesterday. Just wanted to highlight that I reposted it here - https://danq.me/calculating-the-ideal-sex-and-the-city-polycule - because I don't think you accept Webmentions or similar and otherwise might not know.

Thanks! Hope your back's feeling better.

**Comment by jpsyx** [comment]
Hi @Dan-Q! Thank you so much for the repost, that is so kind of you. And I'm glad you enjoyed the talk! The contact page in my form has been fixed now, the API token for the email service had expired. Thanks for flagging that.

I had actually not considered Webmentions before so I will look into that!
